apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: devai

commonLabels:
  app: devai-lab
  managed-by: kustomize

resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - serviceaccount.yaml
  - pvc.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
