apiVersion: v1
kind: Service
metadata:
  name: devai
  namespace: devai
  labels:
    app: devai-lab
spec:
  type: ClusterIP
  ports:
    - name: jupyter
      port: 8888
      targetPort: 8888
      protocol: TCP
  selector:
    app: devai-lab
