apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: devai

resources:
  - ../../base
  - storageclass.yaml

commonLabels:
  cloud: aws

patches:
  - path: ingress-patch.yaml
  - path: serviceaccount-patch.yaml
