apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: devai
  annotations:
    kubernetes.io/ingress.class: gce
    kubernetes.io/ingress.global-static-ip-name: devai-ip
    networking.gke.io/managed-certificates: devai-cert
    kubernetes.io/ingress.allow-http: "false"
