apiVersion: v1
kind: ServiceAccount
metadata:
  name: devai
  annotations:
    # GCP Workload Identity
    # Replace with actual service account from Terraform
    iam.gke.io/gcp-service-account: devai-lab@PROJECT_ID.iam.gserviceaccount.com
