apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: devai-storage
  labels:
    app: devai-lab
provisioner: filestore.csi.storage.gke.io
parameters:
  tier: standard
  network: default
allowVolumeExpansion: true
volumeBindingMode: Immediate
