apiVersion: v1
kind: ServiceAccount
metadata:
  name: devai
  annotations:
    # Azure Workload Identity
    # Replace with actual client ID from Terraform
    azure.workload.identity/client-id: CLIENT_ID
  labels:
    azure.workload.identity/use: "true"
